// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AnalyzeLogFile() {
  return window['go']['main']['App']['AnalyzeLogFile']();
}

export function AnalyzeLogString(arg1) {
  return window['go']['main']['App']['AnalyzeLogString'](arg1);
}

export function CompareJSON(arg1, arg2) {
  return window['go']['main']['App']['CompareJSON'](arg1, arg2);
}

export function CompareJSONWithOptions(arg1, arg2, arg3) {
  return window['go']['main']['App']['CompareJSONWithOptions'](arg1, arg2, arg3);
}

export function FormatJSON(arg1) {
  return window['go']['main']['App']['FormatJSON'](arg1);
}

export function GetDefaultNormalizeOptions() {
  return window['go']['main']['App']['GetDefaultNormalizeOptions']();
}

export function GetJSONPaths(arg1) {
  return window['go']['main']['App']['GetJSONPaths'](arg1);
}

export function OpenJSONFile() {
  return window['go']['main']['App']['OpenJSONFile']();
}

export function ValidateJSON(arg1) {
  return window['go']['main']['App']['ValidateJSON'](arg1);
}
