// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {loganalyzer} from '../models';
import {diff} from '../models';
import {main} from '../models';
import {paths} from '../models';

export function AnalyzeLogFile():Promise<loganalyzer.AnalysisResult>;

export function AnalyzeLogFilePath(arg1:string):Promise<loganalyzer.AnalysisResult>;

export function AnalyzeLogString(arg1:string):Promise<loganalyzer.AnalysisResult>;

export function CompareJSON(arg1:string,arg2:string):Promise<diff.DiffResult>;

export function CompareJSONWithOptions(arg1:string,arg2:string,arg3:main.NormalizeOptions):Promise<diff.DiffResult>;

export function CompareLogAnalyses(arg1:loganalyzer.AnalysisResult,arg2:loganalyzer.AnalysisResult,arg3:string,arg4:string):Promise<loganalyzer.ComparisonResult>;

export function CompareLogFiles(arg1:string,arg2:string):Promise<loganalyzer.ComparisonResult>;

export function FormatJSON(arg1:string):Promise<string>;

export function GetDefaultNormalizeOptions():Promise<main.NormalizeOptions>;

export function GetJSONPaths(arg1:string):Promise<paths.PathResult>;

export function OpenJSONFile():Promise<string>;

export function OpenJSONFileWithPath():Promise<main.FileResult>;

export function ReadFilePath(arg1:string):Promise<string>;

export function SelectAndAnalyzeLogFile():Promise<main.LogFileResult>;

export function SelectAndCompareLogFiles():Promise<loganalyzer.ComparisonResult>;

export function ValidateJSON(arg1:string):Promise<string>;
