// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {loganalyzer} from '../models';
import {diff} from '../models';
import {main} from '../models';
import {paths} from '../models';

export function AnalyzeLogFile():Promise<loganalyzer.AnalysisResult>;

export function AnalyzeLogString(arg1:string):Promise<loganalyzer.AnalysisResult>;

export function CompareJSON(arg1:string,arg2:string):Promise<diff.DiffResult>;

export function CompareJSONWithOptions(arg1:string,arg2:string,arg3:main.NormalizeOptions):Promise<diff.DiffResult>;

export function FormatJSON(arg1:string):Promise<string>;

export function GetDefaultNormalizeOptions():Promise<main.NormalizeOptions>;

export function GetJSONPaths(arg1:string):Promise<paths.PathResult>;

export function OpenJSONFile():Promise<string>;

export function ValidateJSON(arg1:string):Promise<string>;
