// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AnalyzeLogFile() {
  return window['go']['main']['App']['AnalyzeLogFile']();
}

export function AnalyzeLogFilePath(arg1) {
  return window['go']['main']['App']['AnalyzeLogFilePath'](arg1);
}

export function AnalyzeLogString(arg1) {
  return window['go']['main']['App']['AnalyzeLogString'](arg1);
}

export function CompareJSON(arg1, arg2) {
  return window['go']['main']['App']['CompareJSON'](arg1, arg2);
}

export function CompareJSONWithOptions(arg1, arg2, arg3) {
  return window['go']['main']['App']['CompareJSONWithOptions'](arg1, arg2, arg3);
}

export function CompareLogAnalyses(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['CompareLogAnalyses'](arg1, arg2, arg3, arg4);
}

export function CompareLogFiles(arg1, arg2) {
  return window['go']['main']['App']['CompareLogFiles'](arg1, arg2);
}

export function FormatJSON(arg1) {
  return window['go']['main']['App']['FormatJSON'](arg1);
}

export function GetAllFileHistory() {
  return window['go']['main']['App']['GetAllFileHistory']();
}

export function GetDefaultNormalizeOptions() {
  return window['go']['main']['App']['GetDefaultNormalizeOptions']();
}

export function GetFileHistory(arg1) {
  return window['go']['main']['App']['GetFileHistory'](arg1);
}

export function GetJSONPaths(arg1) {
  return window['go']['main']['App']['GetJSONPaths'](arg1);
}

export function GetJSONPathsWithContainers(arg1, arg2) {
  return window['go']['main']['App']['GetJSONPathsWithContainers'](arg1, arg2);
}

export function GetMostRecentFilePath(arg1) {
  return window['go']['main']['App']['GetMostRecentFilePath'](arg1);
}

export function OpenJSONFile() {
  return window['go']['main']['App']['OpenJSONFile']();
}

export function OpenJSONFileWithPath() {
  return window['go']['main']['App']['OpenJSONFileWithPath']();
}

export function ReadFilePath(arg1) {
  return window['go']['main']['App']['ReadFilePath'](arg1);
}

export function SaveFilePathToHistory(arg1, arg2) {
  return window['go']['main']['App']['SaveFilePathToHistory'](arg1, arg2);
}

export function SelectAndAnalyzeLogFile() {
  return window['go']['main']['App']['SelectAndAnalyzeLogFile']();
}

export function SelectAndCompareLogFiles() {
  return window['go']['main']['App']['SelectAndCompareLogFiles']();
}

export function ValidateJSON(arg1) {
  return window['go']['main']['App']['ValidateJSON'](arg1);
}
